# netlify.toml
[build]
  functions = "netlify/functions"
  environment = { SECRETS_SCAN_OMIT_KEYS = "DISCORD_CLIENT_ID,DISCORD_REDIRECT_URI" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Make sure env vars are available locally
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = false