export default {
    title: 'Fantasy Forge Introduction',
    baseUrl: 'http://localhost:5173',

    steps: [
        {
            narrate: 'Welcome to Fantasy Forge, the player investment market where you fuel the players you believe in.',
            action: 'navigate',
            url: 'http://localhost:5173/forge',
            pauseAfter: 1000,
        },
        {
            narrate: 'The Forge runs on a bonding curve. The more people invest in a player, the higher their Spark price rises. Early believers are rewarded. You start with three free Sparks to get going.',
            action: 'wait',
            duration: 500,
            pauseAfter: 800,
        },
        {
            narrate: 'At the top you can see a featured player with their price chart. Hit the shuffle button to discover different players.',
            action: 'click',
            selector: 'button svg.lucide-shuffle',
            highlight: true,
            pauseAfter: 800,
        },
        {
            narrate: 'Spark prices are driven by two forces: demand from the bonding curve, and a weekly performance score that compares each player against others in the same role.',
            action: 'scroll',
            scrollY: 0,
            selector: '[data-tutorial="hero-perf"]',
            highlight: true,
            pauseAfter: 800,
        },
        {
            narrate: 'Use the search bar to find any player by name, team, or role.',
            action: 'click',
            selector: 'input[data-tutorial="search-input"]',
            highlight: true,
            pauseAfter: 600,
        },
        {
            narrate: 'You can sort players by highest value, biggest gainers, most popular, and more.',
            action: 'scroll',
            scrollY: 500,
            selector: 'select',
            highlight: true,
            pauseAfter: 800,
        },
        {
            narrate: 'Each player row shows their current price, recent price change, and total Sparks invested. Green means rising, red means cooling off.',
            action: 'scroll',
            scrollY: 800,
            selector: '.forge-player-row-wrapper',
            highlight: true,
            pauseAfter: 1000,
        },
        {
            narrate: 'Now let us check the portfolio tab to see your investments.',
            action: 'click',
            selector: 'button:has-text("My Sparks")',
            pauseAfter: 1000,
        },
        {
            narrate: 'My Sparks shows every player you have invested in, your total portfolio value, and your profit or loss on each position.',
            action: 'wait',
            duration: 500,
            pauseAfter: 1000,
        },
        {
            narrate: 'Head over to Contracts to find challenges that reward you with bonus Sparks for completing objectives like investing in multiple players or growing your portfolio.',
            action: 'click',
            selector: 'button:has-text("Contracts")',
            pauseAfter: 1200,
        },
        {
            narrate: 'Finally, the Hall of Flame leaderboard ranks all investors by portfolio value. Compete to become the top forge master.',
            action: 'click',
            selector: 'button:has-text("Hall of Flame")',
            pauseAfter: 1200,
        },
        {
            narrate: 'That is Fantasy Forge. Claim your three free Sparks, complete challenges to earn more, and climb the leaderboard. Good luck.',
            action: 'wait',
            duration: 500,
            pauseAfter: 1000,
        },
    ],
}
